CREATE TABLE IF NOT EXISTS invites(id SERIAL PRIMARY KEY,inviter_id BIGINT,invitee_id BIGINT,status TEXT);
CREATE TABLE IF NOT EXISTS role_rewards(role_id BIGINT PRIMARY KEY,points INT);
CREATE TABLE IF NOT EXISTS products(id SERIAL PRIMARY KEY,name TEXT,price INT,type TEXT,status BOOLEAN DEFAULT TRUE);
CREATE TABLE IF NOT EXISTS orders(id SERIAL PRIMARY KEY,user_id BIGINT,product_id INT,status TEXT);
